### ISSUE TITLE
Colors in dark mode 

### ISSUE THREAD

**Issue by rlaarmqua** [zesch/advanced-data-science#4]
In dark mode, code blocks do not have a distinguishable background (as the light gray in light mode) and everything that is dark blue in light mode remains dark blue and is hard to read (e.g. the links under "Previous" and "Next")

**Comment by giggity-hub** [comment]
I changed the color palette. Lemme know what you think
[view website](https://zesch.github.io/advanced-data-science/)

**Comment by rlaarmqua** [comment]
Looks good to me! :-)
