### ISSUE TITLE
Deploying to Vercel

### ISSUE THREAD

**Issue by giggity-hub** [zesch/advanced-data-science#5]
For an easier workflow i would suggest to deploy the page with Vercel. 
I can not set this up myself since i am not the owner of the repository but it takes only like 3 clicks 
+ [create new Vercel Project](https://vercel.com/new)
+ [Docusaurus Vercel Documentation](https://docusaurus.io/docs/deployment#deploying-to-vercel)

**Comment by zesch** [comment]
Done, but there seem to be problems
https://advanced-data-science.vercel.app

**Comment by giggity-hub** [comment]
Thanks. 
looks like we can't deploy to gh-pages and vercel at the same time since they require different configurations.
I'll change the config for a vercel deploy for now so that we can compare both workflows.

**Comment by giggity-hub** [comment]
Works now. 
But there are still some minor issues with images not loading in vercel.
